### ISSUE TITLE
add binaries to each release

### ISSUE THREAD

**Issue by billhathaway** [cloudson/pizzeria#4]
This would let people use it easily who aren't go developers.

**Comment by filhodanuvem** [comment]
Nice @billhathaway ! Do you know some website to generate binaries with different OS targets ? It would be a nice project, otherwise we can build it using docker instances.

**Comment by billhathaway** [comment]
You can cross-compile with go pretty easily  

```
for arch in linux darwin windows
do
   GOOS=$arch go build -o pizzeria.$arch  
done  
```

file pizzeria.*
pizzeria.darwin:  Mach-O 64-bit executable x86_64
pizzeria.linux:   ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
pizzeria.windows: PE32+ executable for MS Windows (console) Mono/.Net assembly

**Comment by filhodanuvem** [comment]
Wow 🙀 , its really amazing. I will do it soon. 
Thank you.

**Comment by filhodanuvem** [comment]
It is done! Thank you again @billhathaway
